##############################################
#############        HOME       ##############
GET http://localhost:5000/dashboard HTTP/1.1

##############################################
#############      PROJECTS     ##############

GET http://localhost:5000/projects/1 HTTP/1.1